<html lang="en">

<head>
    <meta charset="utf-8">
    <title>User logs</title>
    <style>
        .clearfix:after {
            content: "";
            display: table;
            clear: both;
        }

        a {
            color: #5D6975;
            text-decoration: underline;
        }

        body {
            position: relative;
            width: 100%;
            height: 29.7cm;
            margin: 0 auto;
            color: #001028;
            background: #FFFFFF;
            font-family: monospace;
            /* font-family: Arial, sans-serif; */
            font-size: 12px;
            /* font-family: Arial; */
        }

        header {
            padding: 10px 0;
            margin-bottom: 30px;
        }

        #logo {
            text-align: center;
            margin-bottom: 10px;
        }

        #logo img {
            /* width: 100%; */
        }

        h1 {
            border-top: 0px solid #5D6975;
            border-bottom: 0px solid #5D6975;
            color: #5D6975;
            font-size: 2.0em;
            line-height: 1.4em;
            font-weight: normal;
            text-align: center;
            margin: 0 0 20px 0;
            background: #DCDCDC;
        }

        .project {
            float: right;
        }

        .project span {
            color: #5D6975;
            text-align: right;
            width: 52px;
            margin-right: 10px;
            display: inline-block;
            padding:2px;
            font-size: 0.8em;
            line-height: 1.6;
        }
        .signature span {
            color: #5D6975;
            text-align: left;
            width: 90px;
            margin-right: 10px;
            display: inline-block;
            padding:2px;
            font-size: 0.8em;
            line-height: 1.6;
        }

        #company {
            float: right;
            text-align: right;
        }

        .project div,
        #company div {
            white-space: nowrap;
            padding:2px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            border-spacing: 0;
            margin-bottom: 20px;
            margin-top: 40px;
        }

        table tr td {
            background: #F5F5F5;
        }

        table th,
        table td {
            text-align: center;
        }

        table th {
            padding: 5px 10px;
            color: #5D6975;
            /*border-bottom: 1px solid #C1CED9;*/
            white-space: nowrap;
            font-weight: normal;
        }

        table .service,
        table .desc {
            text-align: left;
        }

        table td {
            padding: 10px;
            text-align: left;
        }

        table td.service,
        table td.desc {
            vertical-align: top;
        }

        table td.unit,
        table td.qty,
        table td.total {
            font-size: 1.0em;
            text-align:right;
        }

        table td.grand {
            border-top: 1px solid #5D6975;
        ;
        }

        #notices .notice {
            color: #5D6975;
            font-size: 1.2em;
        }

        footer {
            color: #5D6975;
            width: 100%;
            height: 30px;
            position: absolute;
            bottom: 0;
            border-top: 1px solid #C1CED9;
            padding: 8px 0;
            text-align: center;
        }
    </style>
</head>

<body>
<header class="clearfix">
    <div id="logo">
        <img src="{{ public_path('storage/logos/'.$logo) }}">
    </div>
    <h1>SYSTEM LOGS</h1>

    <div class="project">
        <div><span>USER</span> {{$user_name}}</div>
        <div><span>FROM</span> {{$from}}</div>
        <div><span>TO</span> {{$to}}</div>
    </div>
</header>
<main>
    <table>
        <thead>
        <tr>
            <th style="text-align:left">Datetime</th>
            <th style="text-align:left">Event</th>
            <th style="text-align:left">IP</th>

        </tr>
        </thead>
        <tbody>


        @foreach($user_data as $data)
            <tr>
                <td class="service">{{$data->created_at}}</td>
                <td class="service">{{$data->event}}</td>
                <td class="service">{{$data->ip}}</td>
            </tr>

        @endforeach

        </tbody>
    </table>
    <div class="signature">
        <div><span>MANAGER SIGN</span> --------------------</div>
        <div><span>DATE</span> --------------------</div>
        <div><span>STAMP</span> --------------------</div>
    </div>
</main>
<footer>
    Logs Generated by {{auth()->user()->name}} on {{(Carbon\Carbon::now())->toDayDateTimeString()}}
</footer>

</body>

</html>
